# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6983a745f31c9d02dfa53e79f08d356b093631326af10127059320dfbe60c08edd110bb0ee5f1744e10c5a0b3afe546c89cbf9159a63057307ac93bfea70c8b

test:
  secret_key_base: ee1303dabb7ef1849f2e1cfb94ba9d2295a234bba34671d5f9e72dc386d0b98c65ab59b4b93bb07b076cc34af593e21e111a5d8b244341381fcb5b045da9df18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
